nodeLinker: node-modules

enableGlobalCache: false

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32

npmRegistryServer: "https://registry.yarnpkg.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools" 